### ISSUE TITLE
Sorting by id or relationships attribute

### ISSUE THREAD

**Issue by IDragonfire** [yahoo/elide#471] opened 2017-05-15 08:01 UTC
Currently it is not possible to `sort` by `id` or `-id`.
Instead you get an `InvalidValueException: Invalid value: <Entity> doesn't contain the field id`

Sorting by an attribute is working like expected.

May related to https://github.com/yahoo/elide/issues/96

Example query:
`https://japi.test.faforever.com/data/player?sort=id`

Did I make something wrong?

## Update
It's look like that it is also not possible to sort by an attribute of a relationship ...

## Example Requests
```java
.get("/parent?sort=id]")
.get("/parent?sort=child.id")
.get("/parent?include=children&sort=child.id")
.get("/parent?include=children&sort=child.name")
```

**Comment by francescoesposito7** [comment] 2017-05-15 09:34
I notice that too.

You have the same issue if you filter like:

`http://localhost:8080/entity?filter[entity.attibute]=value`

**Comment by IDragonfire** [comment] 2017-05-15 09:50
@francescoesposito With filtering I have no problems, but we use `RSQL`...
id Filter `https://japi.test.faforever.com/data/player?page[size]=6&filter=id==1`
ann attribute filter are working `https://japi.test.faforever.com/data/player?page[size]=6&filter=login==test`

**Comment by francescoesposito7** [comment] 2017-05-15 09:56
My fault! thanks for your answer!

**Comment by francescoesposito7** [comment] 2017-05-15 09:59
Anyway i've a little problem as you can see in this issue #466.

What's wrong with my elide's implementation?Any idea?Thank a lot for any suggestion

**Comment by IDragonfire** [comment] 2017-05-15 22:24
I don't want to open another issue, but it is also not possible to `sort` by an `attribute` of a relationship ....

**Comment by IDragonfire** [comment] 2017-05-16 12:24
Example queries
```
.get("/parent?include=children&sort=id]")
.get("/parent?include=children&sort=child.id")
.get("/parent?include=children&sort=child.name")
```

**Comment by DeathByTape** [comment] 2017-05-16 16:09
I think we simply missed the sorting by id. I have added a PR here: https://github.com/yahoo/elide/pull/473

re: sorting by relationship attribute. In our old sort processor, it was a known/documented limitation that we couldn't sort in this way. However, with `Sorting.java` I am not aware of any reasons we _couldn't_ do this, only having to think about how it should work :)

Since sorting and pagination are closely related, we would need to reason about what "sane" semantics would be for making such a request. The lowest hanging fruit would be to first determine should we sort the top-level objects by the relationships or just sort the relationships themselves? If I recall correctly from my last read, the JSON API spec is a bit quiet on this :( (perhaps deliberately). 

We'll start here :) @IDragonfire what are you intending by such a query?

**Comment by IDragonfire** [comment] 2017-05-16 22:35
Mostly sorting on `@ManyToOne` relations are needed, e.g. we have a `clan` and `player` type ...
Each `clan` has one `leader` from type `player`. Potential a `player` can be leader of multiple `clans`.
If we list the clans we want to allowing sorting by `leaders`

``` java
.get("/clan?include=leader&sort=leader.name")
```
If you don't support this we must introduce a `@ComputedAttribute` for the `leadername`. or does another way exists?

btw. same problem existing for a similiar use case ...
We currently show the number of members of a clan.
Multiple `players` can be a `member` of a clan.
In the UI we just count the number of element in the `members` relationships of the `clan`.
Sorting is not supported, e.g. over

``` java
.get("/clan?i&sort=members")
```
(members is an array of entities of type `player`)

So at least for this use case I need a  `@ComputedAttribute`, or?

**Comment by DeathByTape** [comment] 2017-05-25 17:59
It sounds like you're trying to sort on an included collection 🤔  that does sound reasonable to me. Though not an ideal solution, a `@ComputedAttribute` may be a quick solution.

Alternatively, you could implement your own sorting grammar by simply extending the existing one and augment it to sort how you would like. You would similarly need to overload the sorting in the datastore though. This is a larger task than the `@ComputedAttribute`, but would likely be more natural for the UI.

@aklish @wcekan @clayreimann how do you guys feel about that? Would it be a sane assumption for us to generally implement sorting by **included** relationships? These relationships _must_ be include or else we wouldn't join them and therefore couldn't paginate correctly.

**Comment by IDragonfire** [comment] 2017-05-30 15:04
In this usecase, `members` is an array of objects and I want at first the `clan` object with the highest count objects inside `members`.

I tried to use `@ComputedAttribute`, without success 
```could not resolve property: membershipCount of: com.faforever.api.data.domain.Clan```

Sample Code
```java
  @Transient
  @ComputedAttribute
  public int getMembershipCount() {
    return getMembers().size();
  }
```

**Comment by micheljung** [comment] 2017-05-31 13:07
Sorting by relationship attribute is a duplicate of #353. Also, see [the workaround I posted there](https://github.com/yahoo/elide/issues/353#issuecomment-280052451)

**Comment by aklish** [comment] 2017-05-31 14:33
Sorting by relationship attributes is actually on our backlog.  Ideally, I would like to also remove any dependency on Hibernate's deprecated Criteria interface as part of that work (and replace everything with JPQL).  It will be a bit before we get to it though (hopefully sometime this summer), so PRs are welcome if this is needed in a hurry.

**Closed** 2017-08-16 19:52 UTC
