### ISSUE TITLE
Envers not supported since 3.x version

### ISSUE THREAD

**Issue by agea** [yahoo/elide#611] opened 2018-01-08 10:59 UTC
It appears that Envers (http://hibernate.org/orm/envers/) is not supported.

To reproduce, just add envers as a dependency in pom.xml

```xml
<dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-entitymanager</artifactId>
    <version>5.0.2.Final</version>
</dependency>
```

and annotate an entity as `@Audited` (this is the User entity from the Example):

```java
@Entity
@Table(name = "user")
@Include(rootLevel = true)
@SharePermission
@Audited
//@CreatePermission(expression = "Prefab.Role.All")
public class User {
    private long id;
    private String name;
    private Role role;
```

When you start the application you get this error:

```
Caused by: java.lang.IllegalArgumentException: Unknown Entity interface java.util.Map
        at com.yahoo.elide.core.EntityDictionary.lookupEntityClass(EntityDictionary.java:936)
        at com.yahoo.elide.core.EntityDictionary.bindEntity(EntityDictionary.java:715)
        at com.yahoo.elide.datastores.hibernate5.HibernateEntityManagerStore.populateEntityDictionary(HibernateEntityManagerStore.java:61)
```

**Comment by DennisMcWherter** [comment] 2018-01-09 16:01
Sorry for the delay, I haven't used envers but will look into this shortly. I don't see any `Map` objects in your code, so I wonder if envers is putting something in. I'll let you know what I come up with.

Thanks for the report!

**Comment by DennisMcWherter** [comment] 2018-01-11 21:52
I haven't forgotten about this; I've just been a bit busy tying up some loose ends elsewhere. Hopefully I'll have a minute to investigate this later this evening.

**Comment by DennisMcWherter** [comment] 2018-01-12 04:08
I finally had a chance to look at this. I wasn't able to reproduce your exact error (with the `java.util.Map`) but I _was_ able to get an analogous error:

```
Caused by: java.lang.IllegalArgumentException: Unknown Entity class org.hibernate.envers.DefaultRevisionEntity
	at com.yahoo.elide.core.EntityDictionary.lookupEntityClass(EntityDictionary.java:936)
	at com.yahoo.elide.core.EntityDictionary.bindEntity(EntityDictionary.java:715)
	at com.yahoo.elide.datastores.hibernate5.AbstractHibernateStore.populateEntityDictionary(AbstractHibernateStore.java:105)
```

After digging a bit deeper I think my original hunch was correct. It looks like envers is actually modifying the classes when you use the `@Audited` annotation.

The real problem though is in how we are scanning and binding entities in hibernate. Basically, we're finding all classes bound in the hibernate session factory and trying to bind the class as an entity. This is obviously incorrect for non-entity classes living in the session factory (from the `getAllClassMetadata()` method). Based on the docs, it seems everything living in `getAllClassMetadata()` *should* be mapped entities, but envers appears to be adding other things (a mapped superclass, for instance, for which I understand is not actually an entity in and of itself).

Assuming that you're not using a custom `RevisionEntity`, I suspect that the difference in our errors (i.e. `Map` vs `DefaultRevisionEntity`) stems from hibernate using an unordered collection and we're likely using slightly different JVM's.

Anyway, I have a proposed fix for the latest elide 4 and elide 3:
https://github.com/yahoo/elide/pull/615
https://github.com/yahoo/elide/pull/616

Feel free to check out either branch and confirm whether or not it fixes your issue in the meantime while we work on getting it released.

Additionally, even though this is a simple fix, it may be worth trying to generate a test case for this to ensure envers continues to work properly.

**Comment by DennisMcWherter** [comment] 2018-01-16 23:18
I have had a chance to finally add a quick test to ensure this doesn't break anything today (I added an `@Audited` annotation to one of our test models).

As a result, I just merged the 3.x fix. I will spin up a new 3.2.2 release tonight (should be available in a few . I will wait for a PR review and can have this merged into the 4.x main line pretty soon too.

As a result, I will close this request for now.

Please feel free to reopen if any issues continue.

**Closed by DennisMcWherter** 2018-01-16 23:18 UTC
