### ISSUE TITLE
Optional<ChangeSpec> is Always Empty

### ISSUE THREAD

**Issue by jstemen** [yahoo/elide#744] opened 2019-02-12 15:37 UTC
It seems like no matter what I do, changeSpec is never populated in the code below.  Is this expected?  I'm trying to setting up logging in my program to capture which fields of an object have changed.  I was hoping that the ChangeSpec would give me just what I needed, but I can't seem to get it to populate.  Any thoughts? 

```
    dictionary.bindTrigger(UserDetails.class, OnUpdatePostCommit.class, new LifeCycleHook<UserDetails>() {
      @Override
      public void execute(UserDetails elideEntity, RequestScope requestScope, Optional<ChangeSpec> changes) {
        if(!changes.isPresent()){
          log.info("No changes found!!");
        }
      }
    });
```

**Comment by aklish** [comment] 2019-02-12 18:00
What version of Elide?

**Comment by jstemen** [comment] 2019-02-12 18:12
com.yahoo.elide:elide-core:4.2.12

**Comment by aklish** [comment] 2019-02-12 19:21
There are three different behaviors for lifecycle hooks:

```
Lifecycle triggers can evaluate for actions on a specific field in a class, for any field in a class, or for the entire class. The behavior is determined by the value passed in the annotation:

An empty value denotes that the trigger should be called exactly once per action on that given entity.
A value matching an entity field/property name denotes that the trigger should be called once per action on that given field/property.
A value set to * denotes that the trigger should be called once per action on all fields or properties in the class that were referenced in the request.
```

There are three different methods in the entity dictionary to get the desired behavior:

```
//Register a lifecycle hook for deletes on the model Book
dictionary.bindTrigger(Book.class, OnDeletePreSecurity.class, callback);

//Register a lifecycle hook for updates on the Book model's title attribute
dictionary.bindTrigger(Book.class, OnUpdatePostCommit.class, "title", callback);

//Register a lifecycle hook for updates on _any_ of the Book model's attributes
dictionary.bindTrigger(Book.class, OnUpdatePostCommit.class, callback, true);
```

It looks like you are calling the first method, which will never have a change spec - since it applies for the entire class (not a specific field).

**Comment by aklish** [comment] 2019-02-13 15:26
I suspect you wanted something like the last call.  Did that resolve your issue?

**Comment by jstemen** [comment] 2019-02-13 15:55
Nope, that didn't resolve my issue.  I have the following follow-up questions:

1. If "dictionary.bindTrigger(Book.class, OnDeletePreSecurity.class, callback);" will never populate "Optional<ChangeSpec> changes", why even have the field in the callback?  It seems like it would be clearer if there were two variants of LifeCycleHook like the following:

One with the change spec always present:
```
public interface LifeCycleHookWithChangeSpec<T> {
    public abstract void execute(T elideEntity,
                                 RequestScope requestScope,
                                 ChangeSpec changes);
}
```

And one without the change spec:
```
public interface LifeCycleHookWithoutChangeSpec<T> {
    public abstract void execute(T elideEntity,
                                 RequestScope requestScope);
}
```
Then the various bindTrigger methods would take one or the other depending on if the given bindTrigger variant plans to actually populate the field.

2. I just tried these two variants too, but they didn't populate the change spec either:
```
 dictionary.bindTrigger(UserDetails.class, OnUpdatePostCommit.class, "*", new LifeCycleHook<UserDetails>() {
      @Override
      public void execute(UserDetails elideEntity, RequestScope requestScope, Optional<ChangeSpec> changes) {
        if(!changes.isPresent()){
          log.info("No changes found!!");
        }
      }
    });
```


```
    dictionary.bindTrigger(UserDetails.class, OnUpdatePostCommit.class, new LifeCycleHook<UserDetails>() {
      @Override
      public void execute(UserDetails elideEntity, RequestScope requestScope, Optional<ChangeSpec> changes) {
        if(!changes.isPresent()){
          log.info("No changes found!!");
        }
      }
    }, true);
```

Just for additional context, I'm looking for a nice way of logging all of the modification requests from clients that update any and all of my resources managed by Elide.

**Comment by aklish** [comment] 2019-02-13 17:25
I tried a quick test but was unable to reproduce:

```
        dictionary.bindTrigger(Book.class, OnUpdatePostCommit.class, new LifeCycleHook<Book>() {
            @Override
            public void execute(Book object, com.yahoo.elide.security.RequestScope scope, Optional<ChangeSpec> changes) {
                if (changes.isPresent()) {
                    System.out.println("Changes are present");
                } else {
                    System.out.println("Changes are not present");
                }
            }
        }, true);
```

![screen shot 2019-02-13 at 11 20 24 am](https://user-images.githubusercontent.com/6979393/52730606-67c8a480-2f81-11e9-99e2-d4742535bc25.png)

Could you provide a minimal repo with the issue?

I'd like to debug what the problem is, but you could also try creating a custom AuditLogger (which might be a better fit for your use case).  That's intended to capture all changes across all resources.

The AuditLogger gets a Log message:
```    public LogMessage(Audit audit, PersistentResource record, Optional<ChangeSpec> changeSpec)
            throws InvalidSyntaxException {
        this(audit.logStatement(), record, audit.logExpressions(), audit.operation(), changeSpec);
    }```

You would need to extend this class and register it with Elide:
```public abstract class AuditLogger {
    protected final ThreadLocal<List<LogMessage>> messages;

    public AuditLogger() {
        messages = ThreadLocal.withInitial(ArrayList::new);
    }

    public void log(LogMessage message) {
        messages.get().add(message);
    }

    public abstract void commit(RequestScope requestScope) throws IOException;

    public void clear() {
        List<LogMessage> remainingMessages = messages.get();
        if (remainingMessages != null) {
            remainingMessages.clear();
        }
    }
}```

**Comment by aklish** [comment] 2019-02-13 19:14
Another thing to check is to verify if the value is actually being changed.

**Comment by wcekan** [comment] 2019-02-15 19:20
@jstemen @aklish 
This appears to be binding to a class but not a field.   ChangeSpec applies only to a field update.

**Comment by wcekan** [comment] 2019-02-15 19:37
Instead try 
```java
dictionary.bindTrigger(Book.class, OnUpdatePostCommit.class, "someField", new LifeCycleHook<Book>() {
```

**Comment by wcekan** [comment] 2019-02-15 20:11
I added tests around this in a new PR to show that it is working as expected.  It does verify the method is constructed correctly, but yours should work fine when bound with the `true` for multiple events.

**Comment by aklish** [comment] 2019-02-28 19:22
@jstemen Any update on this?  We were never able to reproduce on our end (see tests added above).   If you can make a sample project that can reproduce, we can debug and fix.  Otherwise we'll likely close the issue.

**Comment by jstemen** [comment] 2019-02-28 19:54
Oh yeah sorry, I got distracted by other things.  I ultimately decided to write a wrapper around my DataStoreTransaction to capture actions on my resource.  This way I got a nice complete view of everything that happened to resource.  I'm then taking these log events for the resource and sending it to a logging system.  Here's a code snippet in case you're curious:

`
package com.company.action.api.common.datastore;

import com.company.action.api.common.ApplicationConstants;
import com.company.action.api.common.entity_logging.LoggableEntity;
import com.company.action.api.common.util.ObjectMapperFactory;
import com.company.action.api.model.action.streamActionHistory;
import com.company.action.api.model.action.streamLogPayload;
import com.company.action.api.model.hibernate.ActionType;
import com.company.action.api.model.stream.AllPurposestreamRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yahoo.elide.core.RequestScope;
import com.yahoo.elide.core.filter.expression.FilterExpression;
import com.yahoo.elide.core.pagination.Pagination;
import com.yahoo.elide.core.sort.Sorting;
import de.danielbechler.diff.ObjectDifferBuilder;
import de.danielbechler.diff.node.DiffNode;
import de.danielbechler.diff.path.NodePath;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.val;

@AllArgsConstructor
public class streamLogDataStoreTransactionWrapper<T extends LoggableEntity>
    implements TypedDataStoreTransaction<T> {
  private final ObjectMapper objectMapper = ObjectMapperFactory.fetchObjectMapper();

  // todo make request context specific
  private final Map<Serializable, T> entityMap;

  private final AllPurposestreamRepository allPurposestreamRepository;
  private final TypedDataStoreTransaction<T> delegate;

  @Override
  public void save(T currentEntity, RequestScope scope) {

    delegate.save(currentEntity, scope);

    val oldObject = entityMap.get(currentEntity.getId());
    DiffNode root = ObjectDifferBuilder.buildDefault().compare(currentEntity, oldObject);

    val pathsOfChanged = new ArrayList<NodePath>();

    root.visit(
        (node, visit) -> {
          if (!node.hasChildren()) {
            // only add leaf nodes
            pathsOfChanged.add(node.getPath());
          }
        });

    streamLogPayload streamPayload =
        streamLogPayload.builder()
            .loggableEntity(currentEntity)
            .pathsOfChangedFields(pathsOfChanged)
            .build();

    streamActionHistory streamActionHistory = makestreamHistory(streamPayload, scope, ActionType.update);
    allPurposestreamRepository.save(streamActionHistory);
  }

  @Override
  public void delete(T loggableEntity, RequestScope scope) {

    delegate.delete(loggableEntity, scope);

    streamLogPayload streamPayload = streamLogPayload.builder().loggableEntity(loggableEntity).build();

    streamActionHistory streamActionHistory = makestreamHistory(streamPayload, scope, ActionType.delete);
    allPurposestreamRepository.save(streamActionHistory);
  }

  @Override
  public void flush(RequestScope scope) {
    delegate.flush(scope);
  }

  @Override
  public void commit(RequestScope scope) {
    delegate.commit(scope);
  }

  @Override
  public void createObject(T loggableEntity, RequestScope scope) {

    delegate.createObject(loggableEntity, scope);

    streamLogPayload streamPayload = streamLogPayload.builder().loggableEntity(loggableEntity).build();

    streamActionHistory streamActionHistory = makestreamHistory(streamPayload, scope, ActionType.create);

    allPurposestreamRepository.save(streamActionHistory);
  }

  @Override
  public T loadObject(
      Class<T> entityClass,
      Serializable id,
      Optional<FilterExpression> filterExpression,
      RequestScope scope) {
    val entity = delegate.loadObject(entityClass, id, filterExpression, scope);
    final T deepCopy;
    try {
      deepCopy = objectMapper.readValue(objectMapper.writeValueAsString(entity), entityClass);
    } catch (IOException e) {
      throw new IllegalArgumentException("failed to clone request object", e);
    }
    entityMap.put(entity.getId(), deepCopy);
    return entity;
  }

  @Override
  public Iterable<T> loadObjects(
      Class<T> entityClass,
      Optional<FilterExpression> filterExpression,
      Optional<Sorting> sorting,
      Optional<Pagination> pagination,
      RequestScope scope) {
    return delegate.loadObjects(entityClass, filterExpression, sorting, pagination, scope);
  }

  @Override
  public void close() throws IOException {
    delegate.close();
  }

  private streamActionHistory makestreamHistory(
      streamLogPayload streamLogPayload, RequestScope scope, ActionType actionType) {
    LoggableEntity loggableEntity = streamLogPayload.getLoggableEntity();
    return streamActionHistory.builder()
        .actionType(actionType)
        .userUuid(loggableEntity.getuserUuid())
        .actionUuid(UUID.randomUUID())
        .entityId(loggableEntity.getId())
        .executorUuid(ApplicationConstants.getAdvocateUuid(scope))
        .orderKey(loggableEntity.getOrderKey())
        .streamLogPayload(streamLogPayload)
        .eventTypeName(loggableEntity.getEventTypeName())
        .build();
  }
}
`
I should also note that I made another wrapper around the basic DataStoreTransaction Interface that casts the type of the object to the expected type.  That's why there are generic types in the method signatures.  

Even though I decided to go a different way, I really appreciate your quick responses.

**Comment by aklish** [comment] 2019-03-03 23:56
Closing the issue.  I wish we knew what the issue was, but two people tried to reproduce and were unable.  Feel free to reopen if you can reproduce it in a small test repo or have any new insights.

**Closed by aklish** 2019-03-03 23:56 UTC
