### ISSUE TITLE
Pagination needs total page and record count

### ISSUE THREAD

**Issue by johnoscott** [yahoo/elide#264] opened 2016-06-16 03:00 UTC
Most pagination user experiences need to know the total number of pages and records e.g.

`Page 6 of 12 | 1999 Records`

JSON API suggests adding this as `meta` data so for a request like:

`api/product?filter[person.surname][infix]=smith&page[number]=6&page[limit]=20`

something like this :

``` JSON
{
"meta": {
   "page": {
     "number": 6,
     "limit": 20,
     "totalPages": 12,
     "totalRecords":1999
   },
data : { ...
```

Can Elide return something like this ?

**Comment by DeathByTape** [comment] 2016-06-16 14:18
This is a good point and sounds pretty reasonable to me.

@aklish @wcekan  @clayreimann -- do we have a way to do this now (if we do, it's escaping me right now)? If we have no such mechanism already existing, are you guys opposed to this proposal?

**Comment by clayreimann** [comment] 2016-06-16 15:38
@DeathByTape I'm not aware of any way we have to do this currently. Sounds like an extension to the `DatastoreTransaction` interface to me. I think it's a good idea though it might add some overhead. It doesn't look like hibernate's results include this information, so we'll probably have to run a separate query to compute this information–unless @wcekan knows about something I didn't see.

**Comment by DeathByTape** [comment] 2016-06-16 15:54
@clayreimann you're probably right. Perhaps it would be useful to guard this with an additional query param to determine whether or not we want to send the count query to return the number of available records.

I suspect a simple `SELECT count(*) FROM ... WHERE ...` _shouldn't_ take an exorbitant amount of time to execute on most tables, but we could minimize the general latency if we have users explicitly enable this behavior.

**Comment by DeathByTape** [comment] 2016-06-16 17:04
@aklish we should probably make an annotation rather than updating the builder, right? It seems to me like you would want to control this on a per-object basis.

**Comment by johnoscott** [comment] 2016-06-16 21:15
agree this should be optional since it will likely require another query to get the count. maybe

**Comment by mjvanleeuwen** [comment] 2016-06-18 17:02
I have made an attempt at this at https://github.com/ActioPtyLtd/elide/commit/1c9f7b6c051cbddd33a28b72a63e685ae32d43d5
and would appreciate any comments. 

At this stage the logic to query for the totals is only implemented for Hibernate5. The code could be made more efficient by using a single Criteria object to first fetch the total first, then apply the pagination limit and offset to load all entities afterwards. However, that would have involved a much bigger change.

A couple of things I am not sure about:
- Ensuring that a commit is triggered when the total is fetched. As the total is being fetched in the same session as the data, it seemed safe to me assume that a commit will be executed.
- How the parent class KeyValMap of Meta was intended to be used. I ended up removing it as parent. 

An annotation to control the inclusion of the page meta data still needs to implemented.

**Comment by mjvanleeuwen** [comment] 2016-06-23 17:03
I am adding the Paginate annotation as suggested in #266. In doing this, I have broken the test
PaginationLogicTest.shouldIgnoreNegativeIndexForCurrentPageAndPageSize() because a negative page number is now being rejected. 

This seems right to me. Is there any situation when a negative page number should be allowed?

**Comment by DeathByTape** [comment] 2016-06-23 21:06
@mjvanleeuwen this is a good question. In general, I would agree with you for any page-based pagination scheme. However, we should generally accept negative indices. If you [look at the pagination section](http://jsonapi.org/format/#fetching-pagination) for the JSON API spec, you will notice that there are other schemes that could be potentially supported (such as offset- or cursor-based pagination). In such a case, a negative index would likely indicate to move back by _n_ pages. Since pagination is per-datastore, I do not know that we want to lock anyone into a particular scheme; the datastore author should be able to choose which is best for their use-case.

Does anyone else have any thoughts here?

**Comment by clayreimann** [comment] 2016-06-23 21:22
@DeathByTape I don't think that breaking the test is necessarily a bad thing, it could be that the test is not in the appropriate place. 

The Hibernate datastore in use is free to reject negative page numbers as it doesn't (yet) have a good way to express that kind of logic and so should be free to return an error since it cannot fulfill the request. However, the fact that Hibernate doesn't know what we're talking about when we say the `page=-4` does not make it an invalid request.

**Comment by DeathByTape** [comment] 2016-06-23 21:31
Agreed. Let me try to recap what I *think* we're both saying:

For the hibernate pagination tests, we should turn the negative number test into something that rejects. I think we're both happy with explicitly rejecting the request (since we don't have it) rather than ignoring it which may cause confusion to a user.

That said, Elide should still be able to pass through negative numbers to the datastore in pagination so that the datastore can decide how to handle this.

This may already be what you're doing (I don't think you've updated your PR with the implementation yet), but as long as it can do those things, I think it should be fine! :)

**Comment by mjvanleeuwen** [comment] 2016-06-23 23:47
Ok, I see where you're coming from. Another datastore implementation might allow negative page numbers or offsets, so such values should not be rejected by the validation in the Pagination class. It's up to the datastore implementation to apply the extra validation if appropriate.

**Comment by IDragonfire** [comment] 2017-05-14 16:19
For all people who find this issue and want to get `totalPages` or `total-pages` in `meta` key of the response.  just append `page[totals]=true` to the request ;)

http://jsonapi.org/examples/#pagination

**Comment by DeathByTape** [comment] 2017-05-15 13:18
@aklish we do have this all implemented by now, correct? Should we close this issue?

**Comment by aklish** [comment] 2017-05-16 03:31
Yes.  It is implemented.  Closing.

**Closed by aklish** 2017-05-16 03:31 UTC
Labels: enhancement, proposal
