### ISSUE TITLE
=in= with or(",")

### ISSUE THREAD

**Issue by songoo** [yahoo/elide#508] opened 2017-08-09 13:32 UTC
Hello, not sure if its bug or if I am missusing, please advice me.

I have documents which "staffs" and "managers" relation property. One of documents has staff with id "1" .

**OK** - returns 1 documents
`(staffs.id=in=(1))`

**OK** - returns 1 documents (when document.managers is not empty)
`(staffs.id=in=(1), managers.id=in=(1))`

**NOT OK** - returns 0 documents (when document.managers **is empty**)
`(staffs.id=in=(1), managers.id=in=(1))`

Even if document have staff with id 1, it is not returned, for some reason even if first part of query
is successfull another part behind "OR" (",") still changes result if ".managers" is empty

Here is full filter options :   
**OK** - 1 result

```
filter:documentStatus.id=in=(10);(staffs.id=in=(1));documentType.id==2
page[size]:10
page[number]:1
refreshModel:false
reload:false
sort:-createdAt
```

**OK** - 1 results (when .managers is not empty)

```
filter:documentStatus.id=in=(10);(staffs.id=in=(1), managers.id=in=(1));documentType.id==2
page[size]:10
page[number]:1
refreshModel:false
reload:false
sort:-createdAt
```

**NOT OK** - 0 results  (when .managers is empty)

```
filter:documentStatus.id=in=(10);(staffs.id=in=(1), managers.id=in=(1));documentType.id==2
page[size]:10
page[number]:1
refreshModel:false
reload:false
sort:-createdAt
```

**Comment by songoo** [comment] 2017-08-09 13:59
Also tried 
`(staffs.id=in=(1), (managers=isnull=false;managers.id=in=(1)))`
Did not helped.

**Comment by songoo** [comment] 2017-08-09 14:45
More simplified example :  

`id==404 and managers.id!=0`

Will return no result, even when document with id 404 exist, but managers are **empty**

**Comment by DeathByTape** [comment] 2017-08-09 15:49
Which version of Elide are you using and which datastore? I know @aklish [has a fairly large refactoring](https://github.com/yahoo/elide/pull/506) in the underlying logic for this in hibernate which may address this, but it hasn't been merged in yet.

For this query:
> OK - returns 1 documents (when document.managers is not empty)
(staffs.id=in=(1), managers.id=in=(1))

Does `document.managers` contain an `id = 1`? If so, this result doesn't make much sense to me with only 1 document returned.

If you let me know the Elide version and datastore I will try to reproduce this locally and take a deeper look. At a glance, most of what you're trying to do appears sane to me as long as the data checks out.

**Comment by DeathByTape** [comment] 2017-08-09 15:57
Also, if you wouldn't mind posting a minimal example of these models just to review the JPA-annotations as well to make sure nothing seems odd there, that would be great.

**Comment by songoo** [comment] 2017-08-09 16:49
Hello, tnx much for response 👍 
_Which version of Elide are you using_ - I was using "3.0.9" but updated today to "3.0.15", but problem still here .
_which datastore?_ - hibernate5
_Does document.managers contain an id = 1? If so, this result doesn't make much sense to me with only 1 document returned._ -  As result I want Document which has record in .staffs or .managers which has id==1 , in my database thats exactly 1 document which has always .staffs with that record. But for some reason .managers has to contain at least one entry (doesnt matter on its id, since `staffs.id=in=(1)`  is always true for that one document) to query work. Both managers and staffers contains same type of objects "staff". 

```
document : 
managers: DS.hasMany('staff'),
staffs: DS.hasMany('staff')
```
(I'll try to add backend annotation also soon)

As i mentioned in post this can be also simulated by 
`id==404 and managers.id!=0`
Where I have in database "document" with id = 404, with no managers, ".managers" is empty, but result is 0 documents. (wild guess was that it can be caused by inner joins in that case, maybe outer instead but thats really just blind guess)

**Comment by songoo** [comment] 2017-08-10 10:45
Hi, models annotations : 

```
@ManyToMany
  @JoinTable(name = "document_staff", joinColumns = @JoinColumn(name = "document_id", referencedColumnName = "ticket_id", nullable = false), inverseJoinColumns = @JoinColumn(name = "staff_id", referencedColumnName = "staff_id", nullable = false))
  public Collection<Staff> getStaffs() {
    return staffs;
  }
@ManyToMany
  @JoinTable(name = "document_manager", joinColumns = @JoinColumn(name = "document_id", referencedColumnName = "ticket_id", nullable = false), inverseJoinColumns = @JoinColumn(name = "manager_id", referencedColumnName = "staff_id", nullable = false))
  public Collection<Staff> getManagers() {
    return managers;
  }
private Collection<Staff> managers;
  private Collection<Staff> staffs;
```

**Comment by aklish** [comment] 2017-08-11 21:51
@songoo Can you either:
1. Turn on Hibernate logging to see what the SQL queries that are running in the failure case.
2. Upgrade to Elide 3.0.16 (this shouldn't fix anything, but should add some logging) and turn on HQL query logging:

https://github.com/yahoo/elide/blob/8152fc2b333d91fb68f9030652710814344b4884/elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/porting/SessionWrapper.java#L42

Then we can see what the DB queries look like.

**Comment by songoo** [comment] 2017-08-17 14:26
Hello, sorry but it took a while to get project working on newest release (little trouble with ordering not recognising properties)

Here are query logs for issued problem.
`DEBUG c.y.e.d.h.porting.SessionWrapper - HQL Query: SELECT COUNT(DISTINCT net_project_oz3_models_Document)  FROM net.project.oz3.models.Document AS net_project_oz3_models_Document  JOIN net_project_oz3_models_Document.staffs net_project_oz3_models_Document_staffs   JOIN net_project_oz3_models_Document.managers net_project_oz3_models_Document_managers   JOIN net_project_oz3_models_Document.documentStatus net_project_oz3_models_Document_documentStatus   JOIN net_project_oz3_models_Document.documentType net_project_oz3_models_Document_documentType  WHERE (((net_project_oz3_models_Document_staffs.id IN (:staffs_id_6ed6f9a3) OR net_project_oz3_models_Document_managers.id IN (:managers_id_71a37be8)) AND net_project_oz3_models_Document_documentStatus.id IN (:documentStatus_id_233c67c8)) AND net_project_oz3_models_Document_documentType.id IN (:documentType_id_3bd665c6))`

`DEBUG c.y.e.d.h.porting.SessionWrapper - HQL Query: SELECT net_project_oz3_models_Document FROM net.project.oz3.models.Document AS net_project_oz3_models_Document  JOIN net_project_oz3_models_Document.staffs net_project_oz3_models_Document_staffs   JOIN net_project_oz3_models_Document.managers net_project_oz3_models_Document_managers   JOIN net_project_oz3_models_Document.documentStatus net_project_oz3_models_Document_documentStatus   JOIN net_project_oz3_models_Document.documentType net_project_oz3_models_Document_documentType  WHERE (((net_project_oz3_models_Document_staffs.id IN (:staffs_id_6ed6f9a3) OR net_project_oz3_models_Document_managers.id IN (:managers_id_71a37be8)) AND net_project_oz3_models_Document_documentStatus.id IN (:documentStatus_id_233c67c8)) AND net_project_oz3_models_Document_documentType.id IN (:documentType_id_3bd665c6))  order by net_project_oz3_models_Document.createdAt desc`

**Comment by aklish** [comment] 2017-08-18 14:42
The HQL queries look correct to me.  If you turn on SQL query logging, you can cut and paste the SQL query and execute it against your database to see if it matches Elide or is different.  Add the following to your logback.xml:

```<logger name=“org.hibernate.SQL” level=“DEBUG” />```

Elide filters the response from the database by reapplying the filter predicates (in memory) and also executing any security filtering you have enabled.  

If you are using security of any kind, I would recommend turning that off next to see if that is the underlying issue.

That would leave only one possibility if the issue is still there - the in memory execution of the filter predicates you passed in the URL.

We can try to build a test case around your example and see if we can reproduce on our end.

**Comment by songoo** [comment] 2017-08-22 08:21
Hello, what kind of JOIN is used, "left" "inner" ? Isnt the problem that when managers join is done and no manager exist to connect whole result row is removed ?

**Comment by aklish** [comment] 2017-08-22 18:53
It is using INNER join.  That is a good catch.  Unfortunately Hibernate 3 doesn't support FULL OUTER joins (that comes in later in 4) and MySQL (latest version) also doesn't support FULL OUTER joins (it is incompatible with the SQL that is generated by Hibernate).   I was attempting to create a branch to test against - but ran into both of these problems.  The Hibernate 3 issue I can work around but the MySQL one is more troublesome.   Are you using MySQL or another DB?

A LEFT OUTER join will help the problem in some cases, but depends on the order of the or clause.

Here are some pointers to the problems I encountered:
https://hibernate.atlassian.net/browse/HHH-2664
https://dev.mysql.com/doc/refman/5.7/en/join.html

**Comment by aklish** [comment] 2017-08-22 19:25
Also see:
https://bugs.mysql.com/bug.php?id=18003

**Comment by aklish** [comment] 2017-08-23 18:12
I think I was mistaken above.  I think a left outer join should be sufficient.  This should be a pretty small change.

**Comment by aklish** [comment] 2017-08-25 22:36
@songoo Closing the issue.  Was able to reproduce with a test and fix with left outer joins.  Please reopen if not resolved.

**Closed by aklish** 2017-08-25 22:36 UTC
